_wandb:
    value:
        cli_version: 0.25.0
        e:
            foqdpgmlc7k556d7omx709vbsv9d9kzd:
                codePath: assignment-1/notebooks/fast_experiments.py
                codePathLocal: notebooks/fast_experiments.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "106301489152"
                        used: "62056837120"
                email: cs23b083@smail.iitm.ac.in
                executable: /usr/bin/python
                git:
                    commit: 46eeeb70ffbdd86922a6f75af0376d856f34fc83
                    remote: https://github.com/mikhil-c/dl-assignments.git
                host: fedora
                memory:
                    total: "12175470592"
                os: Linux-6.18.13-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/mikhil/Mikhil/Courses/DA courses/Sem-6/DA6401/dl-assignments/assignment-1/notebooks/fast_experiments.py
                python: CPython 3.14.3
                root: /home/mikhil/Mikhil/Courses/DA courses/Sem-6/DA6401/dl-assignments/assignment-1
                startedAt: "2026-03-07T15:14:00.984861Z"
                writerId: foqdpgmlc7k556d7omx709vbsv9d9kzd
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 1
                - 2
                - 5
                - 53
            "2":
                - 1
                - 2
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
hidden_size:
    value:
        - 128
        - 64
        - 32
num_layers:
    value: 3
optimizer:
    value: momentum
